// Dizionario dei termini sanitari con tutte le voci richieste (senza descrizione)
const dizionarioSanitario = [
    {
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: BASTONI CANADESI
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO 
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA :
SINONIMI: Bastoni da deambulazione
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: BUSTO O CORSETTO ORTOPEDICO
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Bustino ortopedico, Corsetto, Tutore del tronco
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: CALZATURE ORTOPEDICHE
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Scarpe ortopediche
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: CALZE O GAMBALETTI ELASTICI
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Calze elastiche, Calze a compressione, Calze terapeutiche
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: CARROZZINA PER DEAMBULAZIONE
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Carrozzella, Sedia a rotelle
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: CAVIGLIERA ELASTICA
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tutore elastico di caviglia
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: CINTO ERNIARIO
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Pancera, Fascia addominale
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: COLLARE CERVICALE
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tutore cervicale, Collare ortopedico
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: CUSCINO ORTOPEDICO
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Cuscino da seduta
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: DIVARICATORE
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tutore divaricatore
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: GINOCCHIERA
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tutore del ginocchio
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: MUTANDA CONTENITIVA
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Mutanda elastica, Pancera contenitiva
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: PLANTARI ORTOPEDICI
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Solette ortopediche
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: RIALZO CALCANEARE
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tallonetta, Zeppa calcaneare
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: SOSPENSORIO
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tutore sospensorio
},
{
COD: 5. PORT
TIPOLOGIA: Termine sanitario
TERMINE: TUTORE
CATEGORIA: PRESIDI ORTOPEDICI (ACQUISTO)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: OPT: SI
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI: Tutore articolare
},
{
COD: 4.LENT
TIPOLOGIA: Termine sanitario
TERMINE: NON DEFINITO
CATEGORIA: LENTI GRADUATE
% RIMBORSO: 30%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: SI TEST VISIVO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI:
},
{
COD: 3.MEDIC
TIPOLOGIA: Termine sanitario
TERMINE: NON DEFINITO
CATEGORIA: MEDICINALI
% RIMBORSO: 40%
MASSIMALE SPECIFICO: "300€ ANNO SOLARE - NUCLEO FAMILIARE - FRANCHIGIA 75€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI:
},
{
COD: 6. PADE
TIPOLOGIA: Termine sanitario
TERMINE: NON DEFINITO
CATEGORIA: "PRESIDI ORTOPEDICI (ADEGUAMENTI)
% RIMBORSO: 20%
MASSIMALE SPECIFICO: 300€ - 3 ANNI AD AVENTE DIRITTO
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA : NO
SINONIMI:
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: PORTA IMPRONTE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: porta impronte dentale
},
{ 
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: APPLICAZIONI DI CALCIO FOSFATO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: applicazione calcio fosfato, trattamento calcio fosfato
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: DENTOPLASTICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: modellazione dentale
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: FACCETTA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: faccetta dentale, veneer
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: PULIZIA PROTESI
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: igiene protesica, pulizia dentiera
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: RICOSTRUZIONE ESTETICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ricostruzione dentale estetica, restauro estetico
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: SEDUTA MOTIVAZIONALE CON PROTOCOLLO GBT
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: seduta motivazionale GBT
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: TERAPIA PARODONTALE NON CHIRURGICA LASER ASSISTITA A QUADRANTE
C CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: terapia parodontale laser
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: TRATTAMENTO REMINERALIZZANTE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: trattamento remineralizzante dentale
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: TRATTAMENTO SMACCHIANTE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: sbiancamento dentale, trattamento smacchiante denti
 },
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: WEENER CERAMICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: veneer ceramica, faccetta ceramica
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: WEENER CERAMICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: veneer ceramica, faccetta ceramica
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: MARCA DA BOLLO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: bollo fiscale, marca fiscale
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: ATTIVAZIONE IMPIANTI
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: attivazione impianto dentale, posizionamento impianto
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: CEMENTAZIONE CORONA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: cementazione protesica, fissaggio corona
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: DIMA CHIRURGICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: guida chirurgica, mascherina chirurgica
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: GBR (ODONTOIATRIA)
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: rigenerazione ossea guidata
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: GRANDE RIALZO DEL SENO MASCELLARE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: rialzo seno mascellare, sinus lift
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: MAGGIORAZIONE PER ELEMENTO IN DISILICATO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: supplemento disilicato, incremento costo disilicato
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: MEMBRANA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: membrana chirurgica, barriera ossea
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: MOLAGGIO SELETTIVO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: molaggio occlusale selettivo
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: PROGETTAZIONE E DIME PER CHIRURGIA IMPLANTARE GUIDATA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: progettazione implantare guidata, guida chirurgica implantare
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: REGOLARIZZAZIONE CRESTA OSSEA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: modellazione cresta ossea, rimodellamento osseo
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: RIGENERAZIONE OSSEA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: rigenerazione ossea, osteo-rigenerazione
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: RIMOZIONE CORONA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: rimozione protesi, estrazione corona
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: RIMOZIONE PERNO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: rimozione perno dentale, estrazione perno
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: SOCKET PREVENTION
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: prevenzione alveolo, protezione socket
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: VISITA CONTROLLO ODONTOIATRICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: controllo odontoiatrico, visita di controllo dentale
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: VITE DI GUARIGIONE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: vite di osteointegrazione, healing screw
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: ANESTESIA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: anestesia locale, anestesia odontoiatrica
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: ANSIOLISI
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: sedazione leggera, sedazione cosciente
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: APPLICAZIONE DEL FARMACO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: somministrazione farmaco, applicazione medicinale
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: ASSISTENZA INFERMIERISTICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: assistenza nurse, supporto infermieristico
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: ASSISTENZA MEDICO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: assistenza medica, supporto medico
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: CODICE UDI MATERIALE RIEMPITIVO
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: codice UDI, identificativo dispositivo
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: DIRITTO FISSO DI SEGRETERIA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: quota segreteria, tassa segreteria
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: SALA OPERATORIA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: sala chirurgica, blocco operatorio
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: SEDAZIONE COSCIENTE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: sedazione controllata, sedazione leggera
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: SUTURA, PUNTI DI
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: punti di sutura, sutura chirurgica
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: TERAPIA ANTIBIOTICA
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: trattamento antibiotico
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: TESSERA PAZIENTE
CATEGORIA: TERAPIE NON RIMBORSABILI 
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: card paziente, badge paziente
},
{
COD: TNON
TIPOLOGIA: Termine sanitario
TERMINE: UTILIZZO DISPOSITIVO DI ANCORAGGIO MEMBRANA
CATEGORIA: TERAPIE NON RIMBORSABILI
% RIMBORSO: 0%
MASSIMALE SPECIFICO: 0€
MASSIMALE GRUPPO: VEDI MASSIMALE SPECIFICO
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: utilizzo ancoraggio membrana, fissaggio membrana
},
{
COD: 2.1.ALAB
TIPOLOGIA: Termine sanitario
TERMINE: DA DEFINIRE
CATEGORIA: ANALISI CLINICHE
% RIMBORSO: 30%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI:
},
{
COD: 2.1.ALAB
TIPOLOGIA: Termine sanitario
TERMINE: DA DEFINIRE
CATEGORIA: ESAMI DI ELABORATORIO
% RIMBORSO: 30%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI:
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: MEDICAZIONE CHIRURGICA (RIMBORSABILE SOLO CON INTERVENTO)
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: MEDICAZIONE POST-OPERATORIA, SUTURA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: ECOCOLORDOPPLER
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ECO COLOR DOPPLER, ECOGRAFIA DOPPLER
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: BIOPSIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: PRELIEVO TESSUTALE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: COLONSCOPIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ESAME COLONICO, COLONOSCOPIA DIGESTIVA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: ECG (ELETTROCARDIOGRAMMA)
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ELETTROCARDIOGRAMMA, ECG
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: ENDOSCOPIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ESAME ENDOSCOPICO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: TONOMETRIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: MISURAZIONE DELLA PRESSIONE INTRAOCULARE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: TOMOGRAFIA A EMISSIONE DI POSITRONI
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: PET
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: CEFALOMETRIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RADIOGRAFIA CEFALOMETRICA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: DIAGNOSI DEL MODELLO DI STUDIO
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: VALUTAZIONE ORTODONTICA DEL MODELLO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: IMPRONTA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: IMPRESSIONE DENTALE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: IMPRONTA PER APPLICAZIONE CORONA PROVVISORIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: IMPRESSIONE PER CORONA TEMPORANEA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: ORTOPANTOMOGRAFIA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: OPG, PANORAMICA DENTALE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: SCANSIONE MASCELLA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: SCANSIONE 3D MASCELLA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: SONDAGGIO PARODONTALE
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ESAME PARODONTALE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: STATUS RADIOGRAFICO
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RADIOGRAFIA COMPLETA, RADIOGRAFIA DI CONTROLLO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: TELECRANIO
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RADIOGRAFIA LATERO-LATERALE DEL CRANIO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: RMN
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RISONANZA MAGNETICA NUCLEARE, RISONANZA MAGNETICA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: TOMOGRAFIA ASSIALE COMPUTERIZZATA
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: TAC, TOMOGRAFIA COMPUTERIZZATA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: CARTELLA PARODONTALE
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: CARTELLA CLINICA PARODONTALE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: CHECK UP ORTODONTICO
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: VALUTAZIONE ORTODONTICA, VISITA ORTODONTICA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: DIAGNOSTICA PRE-SEDAZIONE
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ESAME PRE-ANESTESICO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: STUDIO DEL CASO
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ANALISI DEL CASO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: VALUTAZIONE FUNZIONALE
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: VALUTAZIONE CLINICA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: OPT
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ORTOPANTOMOGRAFIA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: RADIOGRAFIA ENDORALE
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RADIO ENDORALE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: RILEVAZIONE IMPRONTE
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: PRESA IMPRONTE
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: SVILUPPO MODELLI ORTODONTICI
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: REALIZZAZIONE MODELLI ORTODONTICI
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: SVILUPPO MODELLO GESSO CON HORTOB
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: REALIZZAZIONE MODELLO GESSO ORTODONTICO
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: STATUS FOTOGRAFICO
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: DOCUMENTAZIONE FOTOGRAFICA ORTODONTICA
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: CONE BEAM CT
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: CBCT, TAC DENTALE 3D
},
{
COD: 2.2 DGN
TIPOLOGIA: Termine sanitario
TERMINE: DENTALSCAN
CATEGORIA: DIAGNOSTICA
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: SCANSIONE DENTALE 3D
},
{
COD: 2.3.TFISI
TIPOLOGIA: Termine sanitario
TERMINE: DA DEFINIRE
CATEGORIA: TERAPIE FISICHE
% RIMBORSO: 20%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.3.TFISI
TIPOLOGIA: Termine sanitario
TERMINE: DA DEFINIRE
CATEGORIA: TERAPIE RIABILITATIVE
% RIMBORSO: 20%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.4.INCH
TIPOLOGIA: Termine sanitario
TERMINE: DA DEFINIRE
CATEGORIA: INTERVENTI CHIRURGICI AMBULATORIALI
% RIMBORSO: 10%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.5.VSPE
TIPOLOGIA: Termine sanitario
TERMINE: PRIMA VISITA
CATEGORIA: VISITE SPECIALISTICHE
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.5.VSPE
TIPOLOGIA: Termine sanitario
TERMINE:
CATEGORIA: VISITE SPECIALISTICHE
% RIMBORSO: 35%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.6.TPSI
TIPOLOGIA: Termine sanitario
TERMINE:
CATEGORIA: PERCORSI PSICOLOGICI
% RIMBORSO: 20%
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.7.VDSA
TIPOLOGIA: Termine sanitario
TERMINE:
CATEGORIA: PERCORSI VALUTAZIONE  DSA
% RIMBORSO: 30% COMPLETAMENTO  PERCORSO
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 2.7.VDSA
TIPOLOGIA: Termine sanitario
TERMINE:
CATEGORIA: TRATTAMENTO DSA
% RIMBORSO: 20% 
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 2) 1000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: 
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: INCAPPUCCIAMENTO DELLA POLPA INDIRETTO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: ?
OPT: ?
VISITA INIZIALE: ?
VISITA FINALE: ?
VALUTAZIONE SANITARIA: ?
SINONIMI: CAPPIA PULPARE INDIRETTO; INDIRECT PULP CAPPING
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PULPOTOMIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: ?
OPT: ?
VISITA INIZIALE: ?
VISITA FINALE: ?
VALUTAZIONE SANITARIA: ?
SINONIMI: AMPUTAZIONE DELLA POLPA; POLPOTOMIA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: VESTIBOLOPLASTICA CON TRAPIANTO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: ?
OPT: ?
VISITA INIZIALE: ?
VISITA FINALE: ?
VALUTAZIONE SANITARIA: ?
SINONIMI: CHIRURGIA DEL VESTIBOLO; AUMENTO DEL VESTIBOLO; TRAPIANTO DI MUCOSA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ALLACCIAMENTO DI DENTE INCLUSO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: APPLICAZIONE DEL BRACKET PER DISINCLUSIONE; ATTACCO ORTODONTICO SU DENTE INCLUSO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: APICECTOMIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RESEZIONE APICALE; CHIRURGIA ENDODONTICA, AVULSIONE DENTE; DISINCLUSIONE CANINI; RIMOZIONE DENTE; RIZECTOMIA; RIZOTOMIA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ESTRAZIONE DENTE/RADICE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: AVULSIONE; EXODONZIA; ESTRATTO; RIMOZIONE  IMPIANTO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ESTRAZIONE DI IMPIANTO A VITE ENDOSSEO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: RIMOZIONE IMPIANTO; RIMOZIONE VITE ENDOSSEA; RIMOZIONE FIXTURE; RIMOZIONE DEL VECCHIO PONTE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: FRENULECTOMIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: FRENULOPLASTICA; ESCISSIONE DEL FRENULO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: FRENULOTOMIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: INCISIONE DEL FRENULO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: GERMECTOMIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO 
SINONIMI: ESTRAZIONE DEL GERME DENTARIO; AVULSIONE DEL GERME
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: INTERVENTO CHIRURGICO ENUCLEAZIONE CISTI
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: ENUCLEAZIONE CISTICA; ASPORTAZIONE CHIRURGICA DI CISTI; CISTECTOMIA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: MAGGIORAZIONE PER PRESTAZIONI IN SEDAZIONE ENDOVENOSA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: SEDAZIONE COSCIENTE; ANESTESIA ENDOVENOSA; IVS
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: OTTURAZIONE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RIPARAZIONE CARIE; COMPOSITO; FILLING; RESTAURO; BUILD UP PREPROTESICO; COMPOSITO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: RICOSTRUZIONE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RICOSTRUZIONE CORONALE; REBUILDING; RICOSTRUZIONE COMPOSITA; CHIRURGIA PREPROTESICA; RICOSTRUZIONE PRE-PROTESICA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: SIGILLATURA DEI SOLCHI
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: SIGILLANTI; SEALANT
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: DEVITALIZZAZIONE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: CURA CANALARE; TRATTAMENTO ENDODONTICO; TERAPIA CANALARE; RITRATTAMENTO CANALARE; TRATTAMENTO ENDODONTICO; RITRATTAMENTO MULTI ASINTOMATICO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ABLAZIONE TARTARO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: DETARTRASI; IGIENE ORALE; PULIZIA DEI DENTI; SCALING; ABT; DETARTRASI; FLUOROPROFILASSI
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: IMPIANTO A VITE (PER ELEMENTO - ESCLUSA PROTESIZZAZIONE)
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: INSERIMENTO IMPIANTO; FIXTURE; VITE ENDOSSEA; POSIZIONAMENTO IMPIANTO; COMPONENTISTICA IMPLANTOPROTESICA; IMPIANTO DENTALE OXY PREMIUM; IMPIANTO SOMMERSO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ALLUNGAMENTO CORONA CLINICA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: CHIRURGIA DI ALLUNGAMENTO CORONALE; CROWN LENGTHENING
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: CURETTAGE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: RASCHIAMENTO; CURETTAGGIO GENGIVALE; FULL MOUTH DISINFECTION
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: GENGIVECTOMIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RESEZIONE GENGIVALE; ESCISSIONE GENGIVALE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: LEMBO GENGIVALE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: CHIRURGIA A LEMBO; SOLLEVAMENTO DEL LEMBO; LEMBO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: LEVIGATURA RADICOLARE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI 
SINONIMI: ROOT PLANING; ABLAZIONE TARTARO SOTTOGENGIVALE; LEVIGATURA SESTANTE; SCALING E ROOT PLANING
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: MUCO-GENGIVALE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: CHIRURGIA MUCO-GENGIVALE; INNESTO DI TESSUTO CONNETTIVO; INNESTO GENGIVALE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: BARRA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: BARRA PALATINA; BARRA DI ANCORAGGIO; DOLDER BAR
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: BOTTONE PER OVERDENTURE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: ATTACCO A BOTTONE; STUD ATTACHMENT; ATTACCO RADICOLARE; ATTACCO LOCATOR
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: BOTTONE RITENTIVO SU BARRA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: CLIP DI RITENZIONE; ATTACCO A SCIVOLAMENTO; ATTACCO SU BARRA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: CAPPETTA PER OVERDENTURE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: COPERCORONA; RADICE CAPPATA; CORONA A CAPPUCCIO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: CORONA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: CAPSULA (NO VISITA FINALE SE SOLO 1); CORONA FISSA; CAPPETTA; MARYLAND (NO VISITA FINALE SE SOLO 1)
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: CORONA PROVVISORIA (ANCHE RINFORZATA)
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: PROVVISORIO; CORONA TEMPORANEA; PROTESIZIONE PROVVISORIA; ELEMENTO PROVVISORIO RINFORZATO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: INTARSIO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: RESTAURO INDIRETTO; ONLAY; INLAY
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: MONCONE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: PERNO MONCONE; ANIMA RADICOLARE; CORE BUILD-UP; ABUTMENT; ATTACCO BALLATTACHMENT
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: MONCONE IMPLANTARE PROVVISORIO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: PILASTRO PROVVISORIO; MONCONE DI GUARIGIONE; ABUTMENT PROVVISORIO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: MONCONE PER IMPIANTO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI 
SINONIMI: ABUTMENT; PILASTRO IMPLANTARE; TRANSFER
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PERNO MONCONE (SINGOLO O DOPPIO)
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: PERNO RADICOLARE FUSO; ANIMA COLATA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PROTESI AVVITATA PER “TORONTO BRIDGE”
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: PROTESI FISSA IBRIDA AVVITATA; TORONTO BRIDGE; PROTESI SU IMPIANTI AVVITATA; PONTE FISSO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PROTESI FISSA ALL ON FOUR
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: RIABILITAZIONE PROTESICA FISSA CON ELEMENTI  IN COMPOSITO SU IMPIANTI
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PROTESI TOTALE RIMOVIBILE PER OVERDENTURE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: OVERDENTURE; PROTESI RIMOVIBILE SU RADICI; PROTESI TOTALE CON ATTACCHI
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: SCOPERTURA IMPIANTO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: REINTERVENTO DI SCOPERTURA; SECONDO TEMPO CHIRURGICO; APERTURA IMPIANTO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: AGGIUNTA DI MICRORETE O RINFORZO SU PROTESI
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: AGGIUNTA DENTE ALLO SCHELETRATO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ATTACCO EXTRACORONALE SU SCHELETRATO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ATTACCO A PRESSIONE; ATTACCO DI PRECISIONE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: ATTACCO INTRACORONALE SU SCHELETRATO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: ATTACCO A SCATOLA; ATTACCO DI PRECISIONE INTRACORONALE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: BARRA DI RINFORZO SU PROTESI RIMOVIBILE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RINFORZO METALLICO; RETE DI RINFORZO; RETINA RI RINFORZO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: CAPPETTA RADICOLARE CON ATTACCO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: COPERTURA RADICOLARE CON ATTACCO; OVERDENTURE SU RADICE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: GANCIO A FILO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: GANCIO IN LEGA; GANCIO ELABORATO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: GANCIO FUSO
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: GANCIO COLATO; GANCIO IN METALLO NOBILE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PROTESI MOBILE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: DENTIERA; PROTESI RIMOVIBILE; PROTESI MOBILE PARZIALE; VALPLAST
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PROTESI MOBILE TOTALE PROVVISORIA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: DENTIERA PROVVISORIA; PROTESI IMMEDIATA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: PROTESI SCHELETRATA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: SI
VISITA FINALE: SI
VALUTAZIONE SANITARIA: SI
SINONIMI: SCHELETRATO; PROTESI PARZIALE RIMOVIBILE METALLICA; PPR; APPARECCHIO SCHELETRICO CON GANCI; ELEMENTO DENTARIO PER PROTESI SCHELETRICA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: RIBASATURA PROTESI
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RIFODERATURA; RIELABORAZIONE BASE PROTESICA; REBASE
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: RIPARAZIONE APPARECCHIO MOBILE O DI CONTENZIONE
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: AGGIUSTATURA; RIPRISTINO; SALDATURA APPARECCHIO
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: RIPARAZIONE CORONA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RICOSTRUZIONE DI CAPSULA; RIPRISTINO CORONA; AGGIUSTA CORONA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: RIPARAZIONE PROTESI MOBILE O SCHELETRATA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RIPARAZIONE DENTIERA; SALDATURA SCHELETRATO; AGGIUNTA DI UN DENTE; RIPARAZIONE FACCETTA
},
{
COD: 1.1 ODONT
TIPOLOGIA: Termine sanitario
TERMINE: SALDATURA PROTESI FISSA
CATEGORIA: ODONTOIATRIA
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: RICONGIUNZIONE PONTICOLO; RIPARAZIONE PONTE; SALDATURA DI UN ELEMENTO
},
{
COD: 1.2 OCONT
TIPOLOGIA: Termine sanitario
TERMINE: ORTODONZIA CONTENZIONE
CATEGORIA: ORTODONZIA 
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: VEDI MASSIMALE GRUPPO
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: APPARECCHIO DI CONTENZIONE
},
{
COD: 1.3 APP
TIPOLOGIA: Termine sanitario
TERMINE: ORTODONZIA FISSO/MOBILE
CATEGORIA: ORTODONZIA 
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: MAX 500€  ARCATA
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: APPARECCHIO FUNZIONALE; APPARECCHIO INTERCETTIVO; BANDAGGIO; DISGIUNTORE A 2 BANDE; ESPANSORE RAPIDO PALATALE
},
{
COD: 1.3 APP
TIPOLOGIA: Termine sanitario
TERMINE: APPARECCHIO MOBILE
CATEGORIA: ORTODONZIA 
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: MAX 500€  ARCATA
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: - 
},
{
COD: 1.3 APP
TIPOLOGIA: Termine sanitario
TERMINE: INVISALIGN
CATEGORIA: ORTODONZIA 
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: MAX 500€  ARCATA
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: SI
VISITA INIZIALE: SI
VISITA FINALE: NO
VALUTAZIONE SANITARIA: SI
SINONIMI: - 
},
{
COD: 1.3 APP
TIPOLOGIA: Termine sanitario
TERMINE: SPLINTAGGIO
CATEGORIA: ORTODONZIA 
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: MAX 500€  ARCATA
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: SI
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI: CONTENZIONE FISSA
},
{
COD: 1.3 APP
TIPOLOGIA: Termine sanitario
TERMINE: SPLINTAGGIO
CATEGORIA: ORTODONZIA 
% RIMBORSO: 10% ; > 2 ANNI ; > 4 ANNI 1° ISCRIZIONE 20% ; < 2 ANNI ; < 4 ANNI 1° ISCRIZIONE
MASSIMALE SPECIFICO: MAX 500€  ARCATA
MASSIMALE GRUPPO: 1) 3000€
PREVENTIVO – PRESCRIZIONE: NO
OPT: NO
VISITA INIZIALE: NO
VISITA FINALE: NO
VALUTAZIONE SANITARIA: NO
SINONIMI:
];

// Elementi DOM
const searchInput = document.getElementById('searchInput');
const searchButton = document.getElementById('searchButton');
const resultsContainer = document.getElementById('resultsContainer');
const categoryButtons = document.querySelectorAll('.category-btn');
const termsCount = document.getElementById('termsCount');
const selectedCategory = document.getElementById('selectedCategory');

// Variabili per filtri
let currentSearchTerm = '';
let currentCategory = 'all';

// Inizializza la visualizzazione
displayTerms(dizionarioSanitario);
updateStats(dizionarioSanitario.length);

// Event listeners
searchInput.addEventListener('input', function() {
    currentSearchTerm = this.value.toLowerCase();
    filterTerms();
});

searchButton.addEventListener('click', () => {
    currentSearchTerm = searchInput.value.toLowerCase();
    filterTerms();
});

categoryButtons.forEach(button => {
    button.addEventListener('click', function() {
        // Rimuovi la classe active da tutti i pulsanti
        categoryButtons.forEach(btn => btn.classList.remove('active'));
        // Aggiungi la classe active al pulsante cliccato
        this.classList.add('active');
        
        currentCategory = this.getAttribute('data-category');
        selectedCategory.textContent = `Categoria: ${getCategoryLabel(currentCategory)}`;
        filterTerms();
    });
});

// Funzione per filtrare i termini in base alla ricerca e alla categoria
function filterTerms() {
    let filteredTerms = dizionarioSanitario;
    
    // Filtra per categoria
    if (currentCategory !== 'all') {
        filteredTerms = filteredTerms.filter(term => term.categoria === currentCategory);
    }
    
    // Filtra per termine de ricerca
    if (currentSearchTerm) {
        filteredTerms = filteredTerms.filter(term => 
            term.termine.toLowerCase().includes(currentSearchTerm) ||
            term.sinonimi.toLowerCase().includes(currentSearchTerm) ||
            term.cod.toLowerCase().includes(currentSearchTerm) ||
            term.tipologia.toLowerCase().includes(currentSearchTerm)
        );
    }
    
    displayTerms(filteredTerms);
    updateStats(filteredTerms.length);
}

// Funzione per visualizzare i termini
function displayTerms(terms) {
    resultsContainer.innerHTML = '';
    
    if (terms.length === 0) {
        resultsContainer.innerHTML = '<div class="no-results">Nessun risultato trovato. Prova con un\'altra ricerca.</div>';
        return;
    }
    
    terms.forEach(term => {
        const termCard = document.createElement('div');
        termCard.classList.add('term-card');
        
        // Evidenziazione del testo cercato
        const highlightText = (text, search) => {
            if (!search || !text) return text || '';
            const regex = new RegExp(`(${search})`, 'gi');
            return text.toString().replace(regex, '<span class="highlight">$1</span>');
        };
        
        termCard.innerHTML = `
            <h3 class="term-name">${highlightText(term.termine, currentSearchTerm)}</h3>
            <p class="term-detail"><span class="detail-label">COD:</span> ${highlightText(term.cod, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Tipologia:</span> ${highlightText(term.tipologia, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Categoria:</span> ${getCategoryLabel(term.categoria)}</p>
            <p class="term-detail"><span class="detail-label">Rimborso:</span> ${highlightText(term.rimborso, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Max Spec:</span> ${highlightText(term.maxSpec, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Max Grup:</span> ${highlightText(term.maxGrup, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Preventivo-Prescrizione:</span> ${highlightText(term.preventivoPrescrizione, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">OPT:</span> ${highlightText(term.opt, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Visita Iniziale:</span> ${highlightText(term.visitaIniziale, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Visita Finale:</span> ${highlightText(term.visitaFinale, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Valutazione Sanitaria:</span> ${highlightText(term.valutazioneSanitaria, currentSearchTerm)}</p>
            <p class="term-detail"><span class="detail-label">Sinonimi:</span> ${highlightText(term.sinonimi, currentSearchTerm)}</p>
        `;
        
        resultsContainer.appendChild(termCard);
    });
}

// Funzione per aggiornare le statistiche
function updateStats(count) {
    termsCount.textContent = `${count} termini trovati`;
}

// Funzione per ottenere l'etichetta della categoria
function getCategoryLabel(category) {
    const labels = {
        'all': 'Tutti',
        'visite': 'Visite',
        'esami': 'Esami',
        'interventi': 'Interventi',
        'farmaci': 'Farmaci',
        'altre': 'Altre Prestazioni'
    };
    return labels[category] || category;
}